version: "3.6"

services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=local
    ports:
      - 3011:3011
    depends_on:
      - db

  db:
    image: 'mongo:4.4.6'
    ports:
      - 27017:27017
    volumes:
      - ~/mongodb/database:/data/db
