
module.exports = {
  Admin: require("../modules/admin/admin.model"),
  Auth: require("../modules/auth/auth.model"),
  RefAuth: require("../modules/ref_auth/ref_auth.model"),
  GameSession: require("../modules/game_session/game_session.model"),
  Image: require("../modules/image/image.model"),
  User: require("../modules/user/user.model"),
  RefUser: require("../modules/ref_user/ref_user.model"),
  RefWallet: require("../modules/ref_wallet/ref_wallet.model"),
  RefTransaction: require("../modules/ref_transaction/ref_transaction.model"),
  Chat: require("../modules/chat/chat.model"),
  ChatMessage: require("../modules/chat_message/chat_message.model"),
  Transaction: require("../modules/transaction/transaction.model"),
  Wallet: require("../modules/wallet/wallet.model"),
  Bet: require("../modules/bet/bet.model"),
  Confirmation: require("../modules/confirmation/confirmation.model"),
  Bank: require("../modules/bank/bank.model"),
  RefRefs: require("../modules/ref_refs/ref_refs.model"),
  RefReferenceTrack: require("../modules/ref_reference_track/ref_reference_track.model"),
  InTransaction: require("../modules/in_transaction/in_transaction.model"),
  OutTransaction: require("../modules/out_transaction/out_transaction.model"),
  Settings: require("../modules/settings/settings.model"),
};
